In [1]:
import os
import sys

sys.path.append("..")
os.chdir("/home/sean/HAI/main_server/hai")

In [2]:
%load_ext autoreload
%autoreload 2
from controllers.tests.learner import Learner
import time

In [3]:
start_time = 1515275700#1515246244-3600#time.time()-3600*1.5
print(start_time)

1515275700


In [27]:
from controllers.tests.learner2 import Learner

cams = ["webcam0", "webcam1"]
learner = Learner()

In [41]:
from controllers.tests.test0106 import get_hue_label
from controllers.youtubeplayer import get_youtube_label
from controllers.irkit import get_tv_label
from sklearn.preprocessing import StandardScaler
from controllers.dbreader.imagereader import ImageReader

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
end_time = start_time + 3600
imreader = ImageReader()
imdata, times = imreader.read_db("koki", start_time, end_time, cams, skip_absent=False, filtered=False)

In [34]:
len(imdata)

860

In [87]:
import numpy as np

for i in range(1, 1000, 10):#len(imdata)):
    label_data, class_names = get_hue_label(start_time, times[i])
    models, misc = learner.update_models(imdata[:i], times[:i], label_data)
    
    X = misc['matrix']
    print(misc['train_labels']['hue']['indices'])
    #print(X.shape, misc['train_labels']['hue']['intervals'], class_names)
    #print(len(misc['train_labels']['hue']['intervals']), len(label_data['hue']))

    for k in range(len(label_data['hue'])):
        interval = misc['train_labels']['hue']['intervals'][k]
        
        if len(interval) <= 0:
            continue
        
        start, end = interval    
        vec = np.mean(X[start:end], axis=0)
        label_name = class_names[label_data['hue'][k][1]]
        
        rep_index = np.argmax(np.sum((X - vec)**2.0, axis=1))
        print(label_name, interval, rep_index)
    print('---')

    #plt.imshow(StandardScaler().fit_transform(X).T, aspect='auto')
    #plt.show()

[]
---
[]
---
[]
---
[]
---
[]
---
[]
---
[]
---
[]
---
[]
---
[82]
白色 [70, 91] 63
---
[82]
白色 [71, 84] 63
---
[82]
白色 [72, 83] 110
---
[82]
白色 [71, 84] 110
---
[82]
白色 [71, 83] 128
---
[82]
白色 [70, 84] 128
---
[82]
白色 [70, 84] 146
---
[ 82 158]
白色 [70, 85] 146
オフ [125, 161] 128
---
[ 82 158]
白色 [71, 85] 146
オフ [157, 171] 128
---
[ 82 158]
白色 [72, 84] 146
オフ [126, 158] 131
---
[ 82 158]
白色 [71, 83] 146
オフ [125, 158] 110
---
[ 82 158 201]
オフ [156, 201] 128
電球色 [156, 201] 128
---
[ 82 158 201]
白色 [71, 84] 200
オフ [142, 158] 131
電球色 [200, 211] 199
---
[ 82 158 201]
白色 [71, 85] 200
オフ [126, 158] 200
電球色 [200, 221] 199
---
[ 82 158 201]
白色 [71, 84] 200
オフ [142, 158] 131
電球色 [200, 231] 199
---
[ 82 158 201 240]
白色 [71, 84] 200
オフ [157, 200] 128
電球色 [200, 241] 199
白色 [200, 241] 199
---
[ 82 158 201 240]
白色 [71, 83] 200
オフ [125, 158] 200
電球色 [158, 201] 128
白色 [201, 251] 199
---
[ 82 158 201 240]
白色 [71, 83] 200
オフ [125, 158] 200
電球色 [158, 201] 128
白色 [201, 261] 199
---
[ 82 158 201 240]
白色 [71,

KeyboardInterrupt: 

In [396]:
import ruptures as rpt

In [404]:
print

619